blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/yowoda/autopep695/discussions
    about: A perfect place to ask questions and get help with issues you are having.